import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { ButtonDemo } from "@/components/Buy-Template";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className={inter.className}>
        <div className=" bg-[#F7F8FF] min-h-screen">
          <div className="py-4 lg:px-24 px-6">
            <NavBar />
            {children}
            <ButtonDemo />
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
